import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebarsQuickstart: SidebarsConfig = {
  quickstartSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebarsQuickstart;
