import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebarsHadron: SidebarsConfig = {
  hadronSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebarsHadron;
