import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Two named sidebars:
 * - tutorialSidebar: main /docs/ landing, /docs/start/*, /docs/products/*.
 *   Curated: persona hub + product hub as collapsible categories, plus cross-links out
 *   to the developer docs and companion doc sites.
 * - developerSidebar: reached from the 'Developer docs' navbar item; the deep sections
 *   (installation, upgrade, architecture, advanced, reference, examples, development, media)
 *   as collapsible categories.
 *
 * Each deep section (and each hub) is wrapped in an explicit `type: 'category'` here so it
 * renders as a collapsible header. Top-level `autogenerated` entries would otherwise be
 * flattened into siblings, and category-index emission would be skipped.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'index',
    {
      type: 'category',
      label: 'Start here',
      link: {type: 'doc', id: 'start/index'},
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'start'}],
    },
    {
      type: 'category',
      label: 'Products',
      link: {type: 'doc', id: 'products/index'},
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'products'}],
    },
    {type: 'link', label: 'Developer docs', href: '/docs/developer-docs'},
    {type: 'link', label: 'Operator', href: '/operator-docs/'},
    {type: 'link', label: 'Hadron', href: '/hadron-docs/'},
  ],
  developerSidebar: [
    'developer-docs',
    {
      type: 'category',
      label: 'Installation',
      link: {
        type: 'generated-index',
        slug: '/installation',
        title: 'Installation',
        description: 'Discover multiple ways to install Kairos across cloud, bare metal, and virtualized environments.',
      },
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'installation'}],
    },
    {
      type: 'category',
      label: 'Upgrade',
      link: {
        type: 'generated-index',
        slug: '/upgrade',
        title: 'Upgrade',
        description: 'Move a running Kairos node forward safely — A/B upgrades, Trusted Boot, and Operator-driven flows.',
      },
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'upgrade'}],
    },
    {
      type: 'category',
      label: 'Architecture',
      link: {
        type: 'generated-index',
        slug: '/architecture',
        title: 'Architecture',
        description: 'Deep dive into Kairos architecture. Here you will learn in detail how the main features of Kairos have been designed.',
      },
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'architecture'}],
    },
    {
      type: 'category',
      label: 'Advanced',
      link: {
        type: 'generated-index',
        slug: '/advanced',
        title: 'Advanced',
        description: 'Sysexts, partitions, bundles, confidential computing, secureboot cert rotation, and other advanced topics.',
      },
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'advanced'}],
    },
    {
      type: 'category',
      label: 'Reference',
      link: {
        type: 'generated-index',
        slug: '/reference',
        title: 'Reference',
        description: 'CLI, APIs, configuration schema, artifact naming, image matrix, FAQ, and troubleshooting.',
      },
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
    {
      type: 'category',
      label: 'Examples',
      link: {
        type: 'generated-index',
        slug: '/examples',
        title: 'Examples',
        description: 'End-to-end scenarios: airgap, FIPS, MetalLB, LocalAI, HA clusters, and more.',
      },
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'examples'}],
    },
    {
      type: 'category',
      label: 'Development',
      link: {
        type: 'generated-index',
        slug: '/development',
        title: 'Development',
        description: 'Contributor workflow, debugging station, and NVIDIA build notes.',
      },
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'development'}],
    },
    {type: 'autogenerated', dirName: 'media'},
    {type: 'link', label: 'Back to main docs', href: '/docs/'},
  ],
};

export default sidebars;
