import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebarsGettingStarted: SidebarsConfig = {
  gettingStartedSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebarsGettingStarted;
