import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebarsOperator: SidebarsConfig = {
  operatorSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebarsOperator;
