import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebarsProviderKubernetes: SidebarsConfig = {
  providerKubernetesSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebarsProviderKubernetes;
